---
- name: Install Java
  apt:
    name: default-jre
    state: present

- name: Elastic Stack APT repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Elastic Stack APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Start and enable Elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  apt:
    name: kibana
    state: present

- name: Start and enable Kibana service
  service:
    name: kibana
    state: started
    enabled: yes

- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Start and enable Logstash service
  service:
    name: logstash
    state: started
    enabled: yes
